name: car_wash_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_offline: ^3.0.0
  global_configs: ^1.1.2
  http: ^1.1.0
  intl: ^0.18.1
  openapi_generator: ^4.10.0
  sqflite: 2.2.8
  uuid:
  pluto_grid: ^7.0.2
  get_it: ^7.2.0
  provider: ^6.0.5
  go_router: ^10.1.0
  flutter_svg: ^2.0.7
  flutter_file_saver: ^0.6.2
  universal_html: ^2.2.3
  flutter_form_builder: ^9.1.0
  form_builder_file_picker: ^4.0.0
  get: ^4.6.5
  syncfusion_flutter_datagrid: ^22.2.9
  logging: ^1.2.0
  url_strategy: ^0.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/TrajanPro.ttf
        - asset: assets/fonts/TrajanPro_Bold.ttf
          weight: 700

